[package]
name = "rimu-eval"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rimu-report = { path = "../rimu-report" }
rimu-expr = { path = "../rimu-expr" }
rimu-value = { path = "../rimu-value" }
rimu-env = { path = "../rimu-env" }
thiserror = "1.0.44"

[dev-dependencies]
pretty_assertions = "1.4.0"
