[workspace]
members = [
    "rimu-meta",
    "rimu-ast",
    "rimu-parse",
    "rimu-value",
    "rimu-eval",
    "rimu",
    "rimu-repl",
    "rimu-cli",
    "rimu-wasm",
]
resolver = "2"

[profile.release]
lto = true

[profile.release.package.rimu-wasm]
opt-level = "s"
