[package]
name = "rimu"
version = "0.0.1"
edition = "2021"
license = "Apache-2.0"
description = "A data structure template system."
repository = "https://github.com/ahdinosaur/rimu"
keywords = []
categories = []
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
miette = "5.10.0"
pretty_assertions = "1.4.0"
regex = "1.9.1"
rhai = { version = "1.15.1", features = ["serde"] }
rimu-value = { path = "../rimu-value" }
serde = { version = "1.0.174", features = ["derive"] }
serde_json = "1.0.103"
serde_yaml = "0.9.25"
thiserror = "1.0.44"
toml = "0.7.6"
normalize-path = "0.2.1"
os_info = "3.7.0"
ryu = "1.0.15"
serde_spanned = "0.6.3"

[dev-dependencies]
datatest-stable = "0.1.3"
map-macro = "0.2.6"

[[test]]
name = "spec"
harness = false
