[package]
name = "rimu"
version = "0.0.1"
edition = "2021"
license = "Apache-2.0"
description = "A data structure template system."
repository = "https://github.com/ahdinosaur/rimu"
keywords = []
categories = []
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
regex = "1.9.1"
rimu-value = { path = "../rimu-value" }
rimu-env = { path = "../rimu-env" }
rimu-eval = { path = "../rimu-eval" }
rimu-expr = { path = "../rimu-expr" }
serde = { version = "1.0.174", features = ["derive"] }
thiserror = "1.0.44"
normalize-path = "0.2.1"

[dev-dependencies]
pretty_assertions = "1.4.0"
map-macro = "0.2.6"
serde_json = "1.0.103"
serde_yaml = "0.9.25"
toml = "0.7.6"
