// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  indent = 12,
  dedent = 13,
  blankLineStart = 14,
  listItemMarker = 15,
  LineComment = 1,
  Template = 2,
  BlockList = 3,
  Null = 4,
  Boolean = 5,
  String = 6,
  Number = 7
