// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {lines, trackIndent} from "./tokens.js"
export const parser = LRParser.deserialize({
  version: 14,
  states: "#`O]QROOPnOPOOOOQP'#Cq'#CqOsQRO'#CcOOQP'#Cp'#CpQOQROOO]QRO'#CeO{QRO'#CpP!TOQO)C>aOOQP-E6c-E6cOOQP,59P,59POOQP'#Cm'#CmOOQP,59[,59[POOO'#Cd'#CdP!TOQO/'3{POOO/'3{/'3{POOO-E6b-E6bPOOO49)g49)g",
  stateData: "!c~O`OSPOS]PQ~ORQOSQOTQOUQO^UO~O]WO~O^UOYVX~ObZOcZO~OP]O`]ObZOcZO~O",
  goto: "!]fPPPPPPPgkqPPPPPPPxPP!R!XTSOUQ^WR`^SROURXRQ[VQ_WRa^QTORYUTVOU",
  nodeNames: "⚠ LineComment Template Null Boolean String Number BlockList",
  maxTerm: 21,
  context: trackIndent,
  skippedNodes: [0,1,8],
  repeatNodeCount: 2,
  tokenData: "*h~R[YZw]^wpq|rs!Ust#r!O!P$^!Q!R%u!R![&s#Y#Z)P#b#c)n#h#i*V~~*c~|Ob~~!RP`~pq|~!XVOr!Urs!ns#O!U#O#P!s#P;'S!U;'S;=`#l<%lO!U~!sOT~~!vRO;'S!U;'S;=`#P;=`O!U~#SWOr!Urs!ns#O!U#O#P!s#P;'S!U;'S;=`#l;=`<%l!U<%lO!U~#oP;=`<%l!U~#wTP~OY#rZ]#r^;'S#r;'S;=`$W<%lO#r~$ZP;=`<%l#r~$aP!Q![$d~$iUU~!Q![$d!g!h${!l!m%p#R#S$d#X#Y${#^#_%p~%OR{|%X}!O%X!Q![%_~%[P!Q![%_~%dSU~!Q![%_!l!m%p#R#S%_#^#_%p~%uOU~~%z]U~!O!P$^!Q![&s!d!e'_!g!h${!l!m%p!q!r'y!z!{(_#R#S&s#U#V'_#X#Y${#^#_%p#c#d'y#l#m(_~&xVU~!O!P$^!Q![&s!g!h${!l!m%p#R#S&s#X#Y${#^#_%p~'bR!Q!R'k!R!S'k#R#S'k~'pRU~!Q!R'k!R!S'k#R#S'k~'|Q!Q!Y(S#R#S(S~(XQU~!Q!Y(S#R#S(S~(bS!Q![(n!c!i(n#R#S(n#T#Z(n~(sSU~!Q![(n!c!i(n#R#S(n#T#Z(n~)SP#T#U)V~)YP#`#a)]~)`P#g#h)c~)fP#X#Y)i~)nOS~~)qP#i#j)t~)wP#`#a)z~)}P#`#a*Q~*VOR~~*YP#f#g*]~*`P#i#j)c~*hOc~",
  tokenizers: [lines, 0],
  topRules: {"Template":[0,2]},
  tokenPrec: 0
})
