// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  endOfLine = 17,
  endOfFile = 18,
  blankLineStart = 19,
  indent = 20,
  dedent = 21,
  listItemMarker = 22,
  LineComment = 1,
  Template = 2,
  BlockList = 3,
  BlockObject = 4,
  BlockEntry = 5,
  BlockKey = 6,
  Identifier = 7,
  String = 8,
  Null = 9,
  Boolean = 10,
  Number = 11
