// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {indentation, trackIndent} from "./tokens.js"
export const parser = LRParser.deserialize({
  version: 14,
  states: "#lO]QROOPnOPOOOOQP'#Cp'#CpOsQRO'#CcOOQP'#Co'#CoQOQROOOxQRO'#CoP!QOQO)C>`O!`QRO,58}O]QRO'#CeOOQP'#Cl'#ClOOQP,59Z,59ZPOOO'#Cd'#CdP!QOQO/'3zPOOO/'3z/'3zOOQP-E6c-E6cOOQP1G.i1G.iOOQP,59P,59PPOOO-E6b-E6bPOOO49)f49)f",
  stateData: "!m~O_OSPOS]PQ~ORQOSQOTQOUQOZRO~O]VO~OeXO~OaYObYO~OP[O_[OaYObYO~O[`Ob`OeXO~OU~",
  goto: "!ZePPPPPPPfjpPPPPPPvPP!P!VTSOXQ]VRb]QWRR_WQZUQ^VRc]QTORaXTUOX",
  nodeNames: "⚠ LineComment Template Null Boolean String Number BlockList",
  maxTerm: 21,
  context: trackIndent,
  skippedNodes: [0,1,8],
  repeatNodeCount: 2,
  tokenData: "*p~R]YZz]^zpq!Prs!Xst#u}!O$a!O!P$f!Q!R%}!R![&{#Y#Z)X#b#c)v#h#i*_~~*k~!POa~~!UP_~pq!P~![VOr!Xrs!qs#O!X#O#P!v#P;'S!X;'S;=`#o<%lO!X~!vOT~~!yRO;'S!X;'S;=`#S;=`O!X~#VWOr!Xrs!qs#O!X#O#P!v#P;'S!X;'S;=`#o;=`<%l!X<%lO!X~#rP;=`<%l!X~#zTP~OY#uZ]#u^;'S#u;'S;=`$Z<%lO#u~$^P;=`<%l#u~$fOe~~$iP!Q![$l~$qUU~!Q![$l!g!h%T!l!m%x#R#S$l#X#Y%T#^#_%x~%WR{|%a}!O%a!Q![%g~%dP!Q![%g~%lSU~!Q![%g!l!m%x#R#S%g#^#_%x~%}OU~~&S]U~!O!P$f!Q![&{!d!e'g!g!h%T!l!m%x!q!r(R!z!{(g#R#S&{#U#V'g#X#Y%T#^#_%x#c#d(R#l#m(g~'QVU~!O!P$f!Q![&{!g!h%T!l!m%x#R#S&{#X#Y%T#^#_%x~'jR!Q!R's!R!S's#R#S's~'xRU~!Q!R's!R!S's#R#S's~(UQ!Q!Y([#R#S([~(aQU~!Q!Y([#R#S([~(jS!Q![(v!c!i(v#R#S(v#T#Z(v~({SU~!Q![(v!c!i(v#R#S(v#T#Z(v~)[P#T#U)_~)bP#`#a)e~)hP#g#h)k~)nP#X#Y)q~)vOS~~)yP#i#j)|~*PP#`#a*S~*VP#`#a*Y~*_OR~~*bP#f#g*e~*hP#i#j)k~*pOb~",
  tokenizers: [indentation, 0],
  topRules: {"Template":[0,2]},
  tokenPrec: 73
})
