// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  indent = 11,
  dedent = 12,
  blankLineStart = 13,
  listItemMarker = 14,
  LineComment = 1,
  Template = 2,
  Null = 3,
  Boolean = 4,
  String = 5,
  Number = 6,
  BlockList = 7
