[package]
name = "rimu-ast"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust_decimal = "1.31.0"
rimu-meta = { path = "../rimu-meta" }

[dev-dependencies]
pretty_assertions = "1.4.0"
