[package]
name = "rimu-token"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rimu-report = { path = "../rimu-report/" }
rust_decimal = "1.32.0"
